name: Feature request
description: Request a feature.
title: "[Feature] "
labels: ["feature", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Request a feature.
        
        Make sure you have searched the existing issues and didn't found something similar.
        The feature you request should not violate Hypixel's rules (for example, macros are not allowed).
  - type: textarea
    id: description
    attributes:
      label: Description
      description: The details about the new feature
      placeholder: Be detailed. Avoid using expressions that are too brief.
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: Reference
      description: If the feature exists in some SkyBlock mod already, link them here.